# Generated by Django 6.1.1 on 2026-09-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('site_location', models.CharField(max_length=250)),
                ('system_size_kw', models.CharField(max_length=20)),
                ('cleaning_number', models.PositiveIntegerField(default=1)),
                ('is_free', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('date', models.DateField()),
                ('manual_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_size_kw', models.CharField(max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cleaning.cleaningjob')),
            ],
        ),
    ]
