# Generated by Django 6.1.1 on 2026-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningjob',
            name='job_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
    ]
