# Generated by Django 6.1.1 on 2026-09-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_cleaningjob_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True)),
                ('system_size_kw', models.DecimalField(decimal_places=3, max_digits=10)),
                ('google_map_link', models.URLField(blank=True)),
                ('first_cleaning_done', models.BooleanField(default=False)),
                ('first_cleaning_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='cleaning.customer')),
            ],
        ),
    ]
