# Generated by Django 6.1.1 on 2026-09-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_customer_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='system_size_kw',
        ),
        migrations.AddField(
            model_name='site',
            name='solar_kw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
