# Generated by Django 6.1.1 on 2026-09-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_remove_site_system_size_kw_site_solar_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningjob',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_jobs', to='cleaning.customer'),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_jobs', to='cleaning.site'),
        ),
    ]
