# Generated by Django 6.1.1 on 2026-09-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0005_cleaningjob_customer_cleaningjob_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
