# Generated by Django 6.1.1 on 2026-09-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0006_alter_site_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningjob',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='cleaningjob',
            name='site_location',
        ),
        migrations.RemoveField(
            model_name='cleaningjob',
            name='system_size_kw',
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to='cleaning.customer'),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to='cleaning.site'),
        ),
    ]
