# Generated by Django 6.1.1 on 2026-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0007_remove_cleaningjob_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvassingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=250)),
                ('solar_kw', models.CharField(blank=True, max_length=20)),
                ('google_map_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('Lead', 'Lead'), ('Customer', 'Customer')], default='Lead', max_length=20)),
            ],
        ),
    ]
