# Generated by Django 6.1.1 on 2026-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_canvassinglocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='solar_kw',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
