# Generated by Django 6.1.1 on 2026-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0009_alter_site_address_alter_site_solar_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
